<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Encode Phrase',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift value',
    '#type' => 'textfield',
    '#description' => t('Please enter a numeric shift value'),
  );

  $form['shift_direction'] = array(
    '#title' => 'Shift direction',
    '#type' => 'textfield',
    '#description' => t('Please enter left or right'),
  );

  $form['phrase'] = array(
    '#title' => 'Phrase',
    '#type' => 'textfield',
    '#description' => t('Please enter a phrase to encode'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Encode Phrase',
  );

  return $form;
}
