<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Encode Phrase',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['cipher_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift value',
    '#type' => 'textfield',
    '#description' => t('Please enter a numeric shift value'),
  );

  $form['shift_direction'] = array(
    '#title' => 'Shift direction',
    '#type' => 'textfield',
    '#description' => t('Please enter left or right'),
  );

  $form['phrase'] = array(
    '#title' => 'Phrase',
    '#type' => 'textfield',
    '#description' => t('Please enter a phrase to encode'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Encode Phrase',
  );

  return $form;
}

function cipher_form_submit($form, &$form_state) {
  $shift_value = (int)$form_state['values']['shift_value'];

  $shift_direction = $form_state['values']['shift_direction'];
  $phrase = $form_state['values']['phrase'];

  $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');

  $alpha_value = array_flip($alphabet);

  $split_phrase = str_split($phrase);
  $count_phrase = count($split_phrase);
  $encripted_phrase = '';

  for($i = 0; $i < $count_phrase; $i++) {
    $encripted_phrase .= $alphabet[($alpha_value[$split_phrase[$i]]+$shift_value)%26];
  };

  $_SESSION['encripted'] = $encripted_phrase;
  $form_state['redirect'] = 'cipher_success_page';
}

function cipher_success() {

    $answer = $_SESSION['encripted'];
    return 'Your encoded phrase is: ' . $answer. '!';
}
